name: Zip and Ship
run-name: ${{ github.actor }} is zipping the modpack
on: 
  push: 
    branches: 
      - '**'
jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.1
        with:
          files: icon.png manifest.json README.md config/
          recursive: false
          dest: modpack.zip
      - uses: actions/upload-artifact@v3
        with:
          name: modpack-artifact
          path: ${{ github.workspace }}/modpack.zip